[package]
name = "amazeing"
version = "0.1.0"
authors = ["Kalabuk Dmitriy <kalabukdima@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
disjoint-sets = "0.4.2"
enum-map = "0.5.0"
sdl2 = "0.32.1"
