[package]
name = "amazeing"
version = "0.1.0"
authors = ["Kalabuk Dmitriy <kalabukdima@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
itertools = "0.8.0"
disjoint-sets = "0.4.2"
rand = "0.6.5"
sdl2 = "0.32.1"

[features]
bench = []
